### ISSUE TITLE
Question regarding polling endpoints

### ISSUE THREAD

**Issue by deanlyoung** [DMBlakeley/homebridge-awair2#216]
@DMBlakeley curious how often (practically speaking) the device profile endpoint might typically get called?

https://github.com/DMBlakeley/homebridge-awair2/blob/f0701c3a452b7b92bf315722b738b04505efb6fa/src/index.ts#L379

**Comment by deanlyoung** [comment]
As well as this one:

https://github.com/DMBlakeley/homebridge-awair2/blob/f0701c3a452b7b92bf315722b738b04505efb6fa/src/index.ts#L458

**Comment by DMBlakeley** [comment]
@deanlyoung, `async getUserInfo()` and `async getAwairDevices()` are both run once at plug-in startup.
