### ISSUE TITLE
Example serial persists on the ignore list

### ISSUE THREAD

**Issue by nielsth** [DMBlakeley/homebridge-awair2#236]
I'm having trouble setting up this plug-in with my Awair. I've followed the instructions provided, and set it up completely using the Homebridge UI interface.

Since I only own one Element, I haven't added any device to the Ignore list. It appears however as if the example serial is stuck on the ignore list.

```
[12/31/2021, 13:50:17] [Awair2] getAwairDevices: number discovered: 1
[12/31/2021, 13:50:17] [Awair2] Error with Serial 000000059328 on ignore list, does not match Awair OUI "708xxx" or is test device (requires development mode enabled to use).
```

**Comment by DMBlakeley** [comment]
@nielsth, thanks for reaching out. It appears that the MAC address for your device is not correctly registered in the Awair database. 

The MAC addresses of your device is obtained from your Awair account at Homebridge startup / plugin initialization. Awair device MAC addresses should begin with "70886B" while your device is reading as "000000" which is the reason for the error. You can find the MAC address of your device on the device label. 

If you select "Development Mode" in the plugin options your device should work as this overrides the "70886B" check.

@deanlyoung, would it be possible for you to check the Awair database to see if this device is correctly listed?

**Comment by nielsth** [comment]
Thanks @DMBlakeley. I'll try that. Any way to fix the MAC address registerion in my Awair account? Or is that irrelevant?

**Comment by DMBlakeley** [comment]
You can pretty much live with the "Development Mode" but I have asked @deanlyoung to check the Awair database. I am sure that Dean will get back to us.

**Comment by nielsth** [comment]
Thanks! Setting it to "Development Mode" did make it work.

**Comment by DMBlakeley** [comment]
Great!

**Comment by deanlyoung** [comment]
Great workaround. We need to update the database with new MAC addresses from production runs. Another way to uniquely identify devices is via the `device_uuid` which should always be available in the database. The drawback is that it isn't as easily discoverable as the MAC printed on the back of the device.

**Comment by deanlyoung** [comment]
@nielsth can you reach out to hello@getawair.com so that we can track down your device's batch and make sure the database is updated / we didn't miss any.

**Comment by nielsth** [comment]
I've sent them an email today. Looks like their support is out until tomorrow, so I guess it'll take some time for them to reply. Will update when I know more.

**Comment by DMBlakeley** [comment]
Closing for now as problem appears to be on Awair side and not with the plugin.

@deanlyoung, agree that `device_uuid` could be an option but conflicts with the ability to easily add devices on the `ignore` list as the S/N or macAddress is printed directly on the device.
