### ISSUE TITLE
Binary sensors for PM2.5 and VOC

### ISSUE THREAD

**Issue by nielsth** [DMBlakeley/homebridge-awair2#242]
**Is your feature request related to a problem? Please describe:**
In the current integration, a binary sensor is only provided for CO2. The PM2.5 and Volatile Organic Compounds data is combined into a general Air Quality sensor. Binary/Alarm sensors can be used more easily to set up notifications and automations, which are useful for switching on Air Purifiers or reminding users to open a window. 

**Describe the solution you'd like:**
Separate Binary/Alarm sensors are added to the Home for:
* PM2.5
* Volatile Organic Compounds

Both Binary/Alarm sensors showing the most recent measurement under the Details view. And change to a triggered state when passing the threshold (based on the levels that are considered harmful in the Awair app, or could be user configured, similar to the CO2 sensor in this plug-in).

Ideally the Air Quality sensor remains and shows measurement for all three Air Quality types in the Details view (so: CO2 Density is added to this view).

**Comment by DMBlakeley** [comment]
@nielsth, thanks for the enhancement request.

Your suggestions are reasonable but not directly supported in the HomeKit/Homebridge framework. HomeKit defines a collection of Services and associated Characteristics. Reference [Apple HomeKit Accessory Protocol](https://developers.apple.com/homekit/faq/). Homebridge in turn conforms to this definition. This framework also defines how HomeKit devices are displayed in the Home app.

With this in mind, the Awair-2 plugin implements the following Services:
* Air Quality Sensor
* Carbon Dioxide Sensor
* Humidity Sensor
* Temperature Sensor

In addition for Awair-Omni, Battery and Occupancy Services are also implemented. 

For each service there are a number of Characteristics that are supported, for example, the Air Quality Sensor Service includes PM2.5 and VOC Characteristics but not CO2

Looking at your last question first, as the CO2 Sensor is separate, the results cannot be grouped with the Air Quality Sensor in the Home app. The CO2 Sensor is also the only one that supports an alert condition that in turn could be used to enable another device. As you note, this is implemented in the plug-in.

Fully agree that having alarm conditions for PM2.5 and VOC could be useful and worth taking a look at but I will have to try to come up with a work around. My thoughts are to implement “soft” switches similar to what I did for display and LED modes for the Omni, Element and R2. Will take a look and let you know when I have something to try.

**Comment by DMBlakeley** [comment]
@nielsth, you may find the following article interesting:

https://linkdhome.com/articles/how-to-trigger-homekit-automations-with-sensor-values

Although HomeKit does not allow triggers based on sensor values, other apps do.

**Comment by deanlyoung** [comment]
Now I see the purpose here... I guess being able to configure the trigger set points via the config would be a good workaround. I think, as mentioned previously, having separate Air Quality accessories (one for TVOCs and a second dedicated to PM2.5) each with their own, for example, "Fair" setpoint would do the trick. Then, you could use the Fair setpoint to trigger an Automation when values go above or below Fair.

However, this does sound like quite a lot of working-around for something that honestly should be a native HomeKit capability 🙃

![image](https://user-images.githubusercontent.com/2523456/148335326-946e8850-0529-475e-9387-e87960ec752c.png)

**Comment by DMBlakeley** [comment]
Looking for some input ...

In order to provide binary sensors for PM2.5 and VOC I will need to create dummy services to provide notifications when the desired limit is exceeded. A plugin which I use that has faced a similar problem is [`homebridge-weather-plus`](https://github.com/naofireblade/homebridge-weather-plus#readme). This plugin implements unsupported functionality as occupancy sensors that trigger on specific limits (CloudCover > 20%, UVIndex > 2, WindSpeed > 4 m/s, Rain, Snow). I believe using the same approach for the Awair plug-in seems reasonable. Thoughts???

I would also like to understand the implementation of `homebridge-weather-plus` a bit better as it provides historical plotting functionality via the Eve app. Would be great to see the overall history also for the Awair devices.

**Comment by nielsth** [comment]
Thanks for the extensive feedback guys. 

@DMBlakeley I figured there would also be a (binary) sensor for PM 2.5 and VOC in HomeKit, but indeed I don't see it in the HAP Specification. I'll file a feature request for this with Apple first. I personally don't feel the need for a workaround by adding "soft" switches, but I don't mind if you do 😉 

@deanlyoung Good to know Air Quality sensors can now also be used to set automations. Didn't see this before. I suppose this was added in iOS 15.x?

@DMBlakeley Historical data in the Eve app sounds interesting. This sure works nicely with the [eveatmo-plugin](https://github.com/skrollme/homebridge-eveatmo#readme) for Netatmo's Weather Station.

**Comment by nielsth** [comment]
FYI: submitted requests with Apple for TVOC sensor (FB9837711) and PM 2.5 sensor (FB9837711) services. Hope they'll be added to HomeKit sometime in the future.

**Comment by DMBlakeley** [comment]
@nielsth, thanks for the quick response.

I am intrigued by the historical graphing function so will look into this first as I think this provides additional functionality which would be useful.

**Comment by DMBlakeley** [comment]
@nielsth & @deanlyoung, I have published v5.9.0@beta which includes support for PM2.5 and VOC sensor limits. To install go to the Homebridge Plugin page, select the options "wrench", select install previous version and you will see v5.9.0-beta listed.

Note that as I added new Services that you either need to remove the Awair2 plugin, reboot, add and reboot to enable new functionality (make sure that you have your Developer key) to enable the functionality. You alternately can delete the Awair device from the Homebridge cache.

Also note that for VOCs, the Awair devices measure `voc` while HomeKit uses `tvoc` so you will see some difference between the Awair app and HomeKit. If you turn on plug-in logging you will see some details.

Please let me know if the new functionality works for you and if find any issues. Wanted you to check out before I push to the `master` branch.

**Comment by DMBlakeley** [comment]
v5.9.2 merged into `master` branch. `beta` branch deleted.

**Comment by ifeign** [comment]
I actually try to avoid unsupported sensor types in my setup, is there a way to disable these binary sensors? I use occupancy sensors as occupancy sensors in my home setup, so this messes with my notifications

**Comment by DMBlakeley** [comment]
@ifeign, I figured that it wouldn't be too long before this request came in. There currently is not a way to enable/disable but I will look at adding the functionality.

**Comment by ifeign** [comment]
Much appreciated. Should I open an issue for tracking it, or should I not
bother since you’re already aware?

**Comment by ifeign** [comment]
Much appreciated. Should I open an issue for tracking it, or should I not
bother since you’re already ~~awair~~ aware?

**Comment by DMBlakeley** [comment]
I am happy if you would like to put in a feature request. I hope to look at in the next couple days.

**Comment by DMBlakeley** [comment]
@ifeign, I have added option to enable/disable the TVOC and PM2.5 binary switches in v5.9.5. If after updating you then restart Homebridge the switches will be removed as the default is "false". Please let me know if you find any issues.

**Comment by ifeign** [comment]
> @ifeign, I have added option to enable/disable the TVOC and PM2.5 binary switches in v5.9.5. If after updating you then restart Homebridge the switches will be removed as the default is "false". Please let me know if you find any issues.

Works perfectly, thank you very much

**Comment by DMBlakeley** [comment]
😊
