### ISSUE TITLE
Homebridge restarts after setting up my Awair Element

### ISSUE THREAD

**Issue by Sir1711** [DMBlakeley/homebridge-awair2#426]
**Describe The Bug:**
After installing the Homebridge it runs perfectly. The HomebridgeAwair 2 Plugin works also, but when I enter my Token from the Awair Element and restart the Homebridge, it gives me the error and is endless restarting. What did I wrong?

**Logs:**
Show the Homebridge logs here, remove any sensitive information.
TypeError: Cannot read properties of undefined (reading 'forEach')
    at AwairPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-awair2/src/index.ts:268:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-awair2 v5.9.10
* **Homebridge Version**: 1.5.1
* **Node.js Version**: v18.12.1
* **NPM Version**: 
* **Operating System**: macOS Ventura

**Comment by DMBlakeley** [comment]
Thanks for reaching out! 

Couple of questions:
- Just to confirm, are your running Homebridge on a Mac running macOS Ventura?
- Can you check that you have entered your Developer Token correctly? This is for your Awair account not a specific device. You can also request your Developer Token directly through the Awair App on your iPhone. From the App, select `Awair+` in the lower right hand corner, then select `Awair APIs`, select `Cloud API` and finally `Get API Token`.

If you have confirmed your Developer Token, can you turn on verbose logging to see the responses from the Awair servers which also might provide a clue.

**Comment by Sir1711** [comment]
Hey! Thanks for your help.
1. yes with Ventura.
2. I have 108 Signs but I copied the code directly with the Copy Button from the page.

**Comment by Sir1711** [comment]
The error also set my HomePod mini to hardreset. I have to do the whole homesetup again.

**Comment by DMBlakeley** [comment]
I have not been informed of this issue before so I really want to understand how to fix this for you!

I have my test and production configurations both running on Macs with macOS Ventura. I have the same versions of homebridge, Awair plugin and node.js. So I do not see this as the issue.

I have 107 characters in my Developer Token. I have reached out to Awair to see if I can get guidance on the correct length. Please make sure that you did not type a "space" before pasting in the Developer Token which you copied from the app. This can easily happen.

Homebridge does not communicate with the HomePod mini so I do not immediately understand the hard reset which you experienced. My experience is that a hard reset of the HomePod mini does not impact the Home setup as this information is also saved on you iPhone. 

Do you have any other plugins running on Homebridge? What types of devices do you have in your Home setup?

Appreciate if you would turn on logging and verbose mode under the "Optional Configuration Setting" for the Awair plugin and share the first few lines. As reference, mine are:
`[11/8/2022, 4:30:22 PM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 4Cxx) is running on port 51758.`
`[11/8/2022, 4:30:23 PM] [Awair2] userInfo: { redacted }`
`[11/8/2022, 4:30:23 PM] [Awair2] getUserInfo: Completed`
`[11/8/2022, 4:30:23 PM] [Awair2] getAwairDevices: # devices discovered`
`[11/8/2022, 4:30:23 PM] [Awair2] getAwairDevices: discovered device: [0] {"name":"Awair Element", ...}`

**Comment by DMBlakeley** [comment]
I believe your issue is that you typed a "space" before pasting in your Developer Token. I added a space before my Developer Token in the Awair setup and received the same error message which you received.

Please clear and reenter your Developer Token to see if this corrects the issue.

**Comment by Sir1711** [comment]
I double checked it several times. I just copy the code from the website or the app. It doesn't work.

here are the lines you asked for:

[11/8/2022, 11:28:39 PM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 8FCE) is running on port 51875.
[11/8/2022, 11:28:39 PM] [Awair2] userInfo: {"code":7,"message":"Tier was not found for user 141700","details":[]}
[11/8/2022, 11:28:39 PM] [Awair2] getUserInfo error: undefined
[11/8/2022, 11:28:40 PM] [Awair2] getAwairDevices error: undefined
[11/8/2022, 11:28:40 PM] TypeError: Cannot read properties of undefined (reading 'forEach')
    at AwairPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-awair2/src/index.ts:268:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Seemes like he can't find my account?

**Comment by Sir1711** [comment]
I insert the Code in the Homebridge Dashboard in my browser right? In the Plug-Ins-Tab

**Comment by DMBlakeley** [comment]
It's looking like your account has not been set up correctly at Awair. You can either go through the Support option in the app or send an email to them directly at [hello@getawair.com](hello@getawair.com). Include the serial number of your device and ask them to verify that your account has been set up and that your Developer token is active.

Please let me know what their response is.

**Comment by DMBlakeley** [comment]
@Sir1711, have you been able to contact Awair to verify the status of your account?

**Comment by DMBlakeley** [comment]
@Sir1711, following up to see if your issue has been resolved.

**Comment by Sir1711** [comment]
@DMBlakeley Hey! No only one response at this time: We've passed this along to our engineering/product team for review. Once we've received some feedback or notification of a resolution to this issue, we'll get back in touch with you accordingly! Please let us know if any other questions come up in the meantime.
 
Lets see

**Comment by DMBlakeley** [comment]
@Sir1711, I have determined that the Developer Token length can vary based on your user number and a token length of 108 is certainly possible. This is no longer a concern. I have had a user whose device was not properly registered on the Awair side but my main contact is no longer working at Awair.

Just want to make sure that you are able to view your Awair Element status in the iOS app?

**Comment by Sir1711** [comment]
@DMBlakeley Thank you for your information and your effort. Yes I can see my Awair element and all stats in the iOS App.

**Comment by Sir1711** [comment]
No not yet...

**Comment by anthonycorbacho** [comment]
@Sir1711 can you give it a try again?

My team released a patch few weeks ago and this issue should be fixed

**Comment by DMBlakeley** [comment]
@Sir1711 have you been able to retry the Awair2 install?

**Comment by Sir1711** [comment]
@DMBlakeley @anthonycorbacho No i havent got enough time at the moment. I will test it after the holidays. Have a good time with your family and thx for the moment.

**Comment by DMBlakeley** [comment]
@Sir1711 going to close for now. Please do not hesitate to reopen if you want support in resolving. Regards, Doug

**Comment by Sir1711** [comment]
@DMBlakeley  A few minutes ago, I got an e-mail from awair: ,,Thank you for your patience here! My engineering team wanted to reach out to confirm they’ve resolved the issue on their end, so I wanted to reach out and see if this issue is persisting for you after ensuring your app is up to date. Any insight you can provide is appreciated, and otherwise, I hope you have a great weekend!"

**Comment by DMBlakeley** [comment]
see Hello @Sir1711, thanks for checking in! Interesting that 

I have not had any issues with the Awair2 plugin and have not received other uproblem reports. v5.10.4 is the latest version. I have an Awair Omni, Awair v2 and Awair Element running with all the features enabled.

I would suggest if you have the Awair2 plugin installed that you do an uninstall through the Homebridge Plugins page followed by a Homebridge restart. Then install the plug-in and enter your Developer Token.  Reference the Awair2 plugin Installation instructions on how to obtain.

Then restart Homebridge and see if you Awair Element is added. If not, please copy the log and send it my way. I can then let you know how to answer the Awair email.

Regards, Doug
