### ISSUE TITLE
Rewording Omni advanced options config-ui-x

### ISSUE THREAD

**Issue by deanlyoung** [DMBlakeley/homebridge-awair2#52]
The title for the field with the 2 in it (screenshot below) isn't very descriptive / kind of confusing. It's not clear what it is meant for.

<img width="979" alt="Screen Shot 2021-01-31 at 08 44 09" src="https://user-images.githubusercontent.com/2523456/106669810-0ed4eb00-6561-11eb-8dd2-855e8691fe98.png">

**Comment by DMBlakeley** [comment]
This is explained a bit better in the Wiki, [Section 3](https://github.com/DMBlakeley/homebridge-awair2/wiki/3.-Awair2-Configuration-Options). 

Basically, as Omni sound level samples are collected, a minimum baseline is determined. Say this is 50.2dBA. The 2db is added to 50.2 (52.2dBA) to establish the upper limit for not-occupied. An additional 0.5dB (52.7dBA) is added to establish the lower limit for occupied. This results in a 0.5dB dead-band. I have found to work well in my home environment. May take a bit of adjustment based on other environments.

Will see if I can improve description in config-ui-x text.

**Comment by DMBlakeley** [comment]
I have updated the wording on the config-ui-x settings and also referred to Wiki Chapter 3 for details. Do these changes address your request?

**Comment by deanlyoung** [comment]
What do you think?

https://github.com/DMBlakeley/homebridge-awair2/pull/55

**Comment by DMBlakeley** [comment]
I like your updates. Only item I see is `occupanceRestart` should be `Reset` rather than `Resume`. I currently have not figured out how to write to the `config.json` file to clear the setting and removed the word `next`. Propose the following:

      "occupancyRestart": {
        "title": "Omni Reset Occupancy Status - reinitialize Occupancy detection measurement on Homebridge reboot.",
        "type": "boolean",
        "default": false,
        "description": "Omni only - reinitialize Occupancy detection measurement to determine unoccupied sound level on Homebridge reboot.",
        "condition": {
          "functionBody": "return model.occupancyDetection === true;"
        }

I think best to merge from my end as I can then bump the revision to `v5.7.2`, update `CHANGELOG.md` and I also want to make some tweaks to the `README.md` file.

**Comment by DMBlakeley** [comment]
I have scrubbed `config.schema.json` and `README.md` files and pushed `v5.7.2` with these changes. Appreciate if you take a look and see if you have any comments or concerns.
