### ISSUE TITLE
Awair Developer token is not valid. Please check that token is entered correctly with no leading spaces.

### ISSUE THREAD

**Issue by pospischil** [DMBlakeley/homebridge-awair2#781]
**Describe Your Problem:**
I'm getting an error with the plugin, it tells me that the token is not valid, but there are no leading/trailing spaces or curly braces.  When I run the test CURL, it works fine:
% curl -X GET \
https://developer-apis.awair.is/v1/users/self/devices \
-H 'Authorization: Bearer TOKENHERE'
{"devices":[{"name":"Aware 2", "deviceId":4348, "deviceType":"awair-r2", "deviceUUID":"awair-r2_4348", "latitude":REDACTED, "longitude":REDACTED, "preference":"GENERAL", "locationName":"REDACTED", "roomType":"BEDROOM", "spaceType":"HOME", "macAddress":"REDACTED", "timezone":"America/New_York"}]}%    

**Logs:**

[9/11/2024, 4:38:41 PM] [Awair2] Initializing Awair2 platform...
[9/11/2024, 4:38:41 PM] [Awair2] Awair Developer token is not valid. Please check that token is entered correctly with no leading spaces.

**Plugin Config:**

{
    "token": "TOKENHERE NO LEADING/TRAILING SPACES OR CURLY BRACES",
    "userType": "users/self",
    "airQualityMethod": "awair-score",
    "endpoint": "15-min-avg",
    "limit": 1,
    "enableTvocPm25": false,
    "occupancyDetection": false,
    "occupancyRestart": false,
    "logging": false,
    "verbose": false,
    "enableModes": false,
    "modeTemp": false,
    "modeTime": false,
    "development": false,
    "platform": "Awair2"
}

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**: 5.12.2
* **Homebridge Version**: v1.8.4 (HAP v0.12.2) (Homebridge D28A)
* **Node.js Version**: v20.17.0
* **NPM Version**: 10.8.2
* **Operating System**: Docker

**Comment by DMBlakeley** [comment]
Does your developer token start with "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9"?

**Comment by pospischil** [comment]
No, it starts with "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

**Comment by DMBlakeley** [comment]
When did you purchase your Awair device? Appears that Awair has changed the initial characters of their Developer token. I had communication with Awair quite some time ago concerning the token and will have to try to dig it up.

**Comment by DMBlakeley** [comment]
The Developer Token is a JWT or JSON Web Token based on your user_id.

It appears that Awair has changed their format and when I check on my web token through the Awair app, I find that I have the same as you.

I will release an update by the end of the week that supports both old and new preamble.

**Comment by pospischil** [comment]
I purchased this many years ago, not sure when it was exactly.  Maybe like 5 or more?

**Comment by pospischil** [comment]
Thanks so much!

**Comment by DMBlakeley** [comment]
I also have an Awair-r2 as well as an Awair-Element and Awair-Omni for testing.

Just released v5.12.3 with support for the new token. Please give it a try and let me know if the plug-in now works for you.

**Comment by pospischil** [comment]
Awesome, I'll give a try ASAP and report back, thanks so much!

**Comment by pospischil** [comment]
That fixed it, thanks!
