### ISSUE TITLE
Node.js 20 no longer supported by plugin

### ISSUE THREAD

**Issue by johnjensenish** [DMBlakeley/homebridge-awair2#831]
**Describe The Bug:**
Using latest version of plugin, I see the following log output:

> [09/12/2024, 12:30:01] The plugin "homebridge-awair2" requires Node.js version of ^18.20.4 || ^22.11.0 which does not satisfy the current Node.js version of v20.18.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF#

The plug-in appears to function normally.

**To Reproduce:**
Install Node 20
Install plugin
Run

**Expected behavior:**
`package.json` should indicate the plugin still supports Node 20.

**Logs:**

```
[09/12/2024, 12:30:01] The plugin "homebridge-awair2" requires Node.js version of ^18.20.4 || ^22.11.0 which does not satisfy the current Node.js version of v20.18.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```

**Plugin Config:**

not relevant

**Screenshots:**

**Environment:** raspberry pi

* **Plugin Version**: 5.12.6
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.18.1
* **NPM Version**: 10.8.2
* **Operating System**: Raspbian

**Comment by DMBlakeley** [comment]
John, thanks for reporting. Will investigate and post a correction. In the meantime, you can roll back to v5.12.5 and you should be fine.

**Comment by DMBlakeley** [comment]
John, I believe that I have addressed operation with node.js v20 and v22 with v5.12.7 of the plugin. Can you confirm?
