### ISSUE TITLE
Temperature as an actionable sensor

### ISSUE THREAD

**Issue by chrisgmbishop** [DMBlakeley/homebridge-awair2#95]
When trying to create an automation, Air quality and Humidity show as sensors but Temp is missing.

**Comment by DMBlakeley** [comment]
Hi Chris, 

Unfortunately this is a limitation of Homekit and not the plugin. 

Apple’s Home app allows triggering automation rules with sensor data, but only those that have an event based behavior such as Motion Sensors, Contact Sensors, and Smoke Sensors. Air Quality and CO2 fall into this category but not temperature or humidity. [Reference.](https://linkdhome.com/articles/how-to-trigger-homekit-automations-with-sensor-values)

You can use a third party HomeKit app such as Eve or Controller to create automations based on sensor values such as temperature. [Reference.](https://linkdhome.com/articles/homekit-automation-guide) You can also use IFTTT to provide notifications of high or low conditions.

Hopefully iOS15 will bring much needed enhancements to HomeKit. 

Regards, Doug

**Comment by DMBlakeley** [comment]
@chrisgmbishop, finding that with iOS15 Temp shows up as a sensor that you can create automations based on temperature.

Regards, Doug
